---
grails:
    profile: web
    codegen:
        defaultPackage: grace.guides
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    groovy:
        template:
            check-template-location: false
    devtools:
        restart:
            additional-exclude:
                - '*.gsp'
                - '**/*.gsp'
                - '*.gson'
                - '**/*.gson'
                - 'logback.groovy'
                - '*.properties'
management:
    endpoints:
        enabled-by-default: true
        web:
            base-path: '/actuator'
            exposure:
                include: '*'
---
spring:
    datasource:
        url: jdbc:h2:mem:gs_spring_boot_data_jpa_dev;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password: ''
    flyway:
        locations: "classpath:db/migration"
